version: 2.1

orbs:
  maven: circleci/maven@2.0.0
  heroku: circleci/heroku@2.0.0
  docker: circleci/docker@2.1.4
  snyk: snyk/snyk@1.5.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run: |
                echo "Install dependencies"
                mvn clean install

  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run: |
                echo "Running tests"
                mvn test
  deploy:
    docker:
      - image:  cimg/node:16.10
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku stack:set container -a recipe-assignment
            heroku container:push web -a recipe-assignment
            heroku container:release web -a recipe-assignment

workflows:
  assignment_workflow:
    jobs:
      - build:
          filters:
            branches:
              ignore: []
            tags:
              only: /^v.*/
      - test:
          requires:
            - build
          filters:
            branches:
              ignore: []
            tags:
              only: /^v.*/
